project_id = "jqnzprikajnjufyuamtt"

[functions.manage-student-verification]
verify_jwt = true

[functions.bulk-signup-students]
verify_jwt = true

[functions.manage-users]
verify_jwt = true

[functions.student-analysis]
verify_jwt = true

[functions.questions-from-images]
verify_jwt = true
