// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uqmrmbifplffwkfsunue.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVxbXJtYmlmcGxmZndrZnN1bnVlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ3NjM0MzksImV4cCI6MjA3MDMzOTQzOX0.C9r0Q5MT_iAzWTMuHFKXwj7lG2mM4zDPDGbEq_AadL8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});